# ======================================================
# TASK 3 -- STOCK MARKET VISUALIZATION PROJECT
# COMPLETE PROFESSIONAL VERSION
# ======================================================

# ------------------------------------------------------
# IMPORTS
# ------------------------------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from config import PATHS
import data_loader

# ------------------------------------------------------
# CREATE OUTPUT FOLDER
# ------------------------------------------------------
os.makedirs(PATHS.OUTPUTS_DIR, exist_ok=True)

# ------------------------------------------------------
# STYLE
# ------------------------------------------------------
sns.set_theme(
    style="whitegrid",
    font_scale=1
)

# ------------------------------------------------------
# COLORS
# ------------------------------------------------------
COLOR_LIGHT = "#FFC8DD"
COLOR_MID = "#FFAFCC"
COLOR_BRIGHT = "#FF4D6D"
COLOR_DARK = "#800F2F"
COLOR_DEEP = "#590D22"

# ======================================================
# LOAD DATA
# Uses data_loader so it reads from Parquet when available,
# consistent with the rest of the pipeline.
# load_latest_day() returns only the most recent trading day
# so all charts always reflect the latest scrape.
# ======================================================
df = data_loader.load_latest_day()

# ======================================================
# IMPORT RESULTS FROM eda.py -- no recalculation here
# stats_results.py is auto-generated by scraper.py via eda.py
# ======================================================
from stats_results import (
    PRICE_MEAN, PRICE_MEDIAN, PRICE_STD, PRICE_SKEW,
    AVG_CHG, Q1, Q3,
    N_TOTAL, N_GAIN, N_LOSS, N_FLAT,
    TOP_SYM, TOP_PCT, BOT_SYM, BOT_PCT,
    SP_CORR, SP_P, SP_STRENGTH, SP_DIRECTION,
    SPEARMAN_MATRIX, U_STAT, MW_P,
    UPPER_FENCE, N_OUTLIERS, OUTLIER_SYMS,
    GAINER_PCT_MED, LOSER_PCT_MED,
)

# Derived display values -- not calculations, just formatting
df["Status"] = np.where(
    df["Change"] > 0, "Gainer",
    np.where(df["Change"] < 0, "Loser", "Flat")
)

mean_price    = PRICE_MEAN      # from eda.py
status_counts = df["Status"].value_counts()
top_stocks    = df.nlargest(10, "% Change")

# Correlation matrix from eda.py (Spearman, correct for skewed data)
corr_cols = ["Price", "Change", "% Change"]
corr = pd.DataFrame(
    SPEARMAN_MATRIX,
    index=corr_cols,
    columns=corr_cols
)

# ======================================================
# HELPER FUNCTIONS
# ======================================================
def style_ax(ax, title):

    ax.set_title(
        title,
        fontsize=14,
        fontweight="bold",
        color=COLOR_DEEP,
        pad=15
    )

    ax.tick_params(
        colors=COLOR_DARK
    )

def save_chart(fig, filename):

    fig.savefig(
        os.path.join(PATHS.OUTPUTS_DIR, filename),
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()

    plt.close(fig)

# ======================================================
# CHART 1 -- MARKET BREADTH
# ======================================================
fig, ax = plt.subplots(figsize=(7, 6))

# Explicit color map so Gainer=green, Loser=red regardless of sort order
COLOR_MAP = {"Gainer": "#2DC653", "Loser": COLOR_BRIGHT, "Flat": "#FFC300"}
pie_colors = [COLOR_MAP.get(s, COLOR_LIGHT) for s in status_counts.index]

ax.pie(
    status_counts.values,
    labels=status_counts.index,
    autopct="%1.1f%%",
    startangle=90,
    colors=pie_colors,
    wedgeprops={
        "edgecolor": "white",
        "linewidth": 2
    }
)

style_ax(
    ax,
    "Market Breadth: Gainers vs Losers"
)

save_chart(
    fig,
    "01_market_breadth.png"
)

# ======================================================
# CHART 2 -- PRICE DISTRIBUTION
# ======================================================
fig, ax = plt.subplots(figsize=(8, 5))

sns.histplot(
    df["Price"],
    bins=20,
    kde=True,
    color=COLOR_BRIGHT,
    edgecolor="white",
    linewidth=1,
    ax=ax
)

ax.axvline(
    mean_price,
    color=COLOR_DEEP,
    linestyle="--",
    linewidth=2,
    label=f"Mean = {mean_price:.2f}"
)

ax.legend()

style_ax(
    ax,
    "Stock Price Distribution"
)

save_chart(
    fig,
    "02_price_distribution.png"
)

# ======================================================
# CHART 3 -- VIOLIN PLOT
# ======================================================
fig, ax = plt.subplots(figsize=(8, 5))

# Changed y from Price to % Change -- more informative since Mann-Whitney
# confirms no significant price difference between gainers and losers
sns.violinplot(
    data=df,
    x="Status",
    y="% Change",
    hue="Status",
    legend=False,
    palette={"Gainer": "#2DC653", "Loser": COLOR_BRIGHT, "Flat": "#FFC300"},
    linewidth=1.5,
    ax=ax
)

style_ax(
    ax,
    "% Change Distribution by Market Direction"
)

save_chart(
    fig,
    "03_violin_plot.png"
)

# ======================================================
# CHART 4 -- TOP PERFORMERS
# ======================================================
fig, ax = plt.subplots(figsize=(9, 6))

sns.barplot(
    data=top_stocks,
    y="Symbol",
    x="% Change",
    hue="Symbol",
    legend=False,
    palette="RdPu",
    ax=ax
)

style_ax(
    ax,
    "Top 10 Performing Stocks"
)

save_chart(
    fig,
    "04_top_performers.png"
)

# ======================================================
# CHART 5 -- CORRELATION HEATMAP
# ======================================================
fig, ax = plt.subplots(figsize=(7, 6))

sns.heatmap(
    corr,
    annot=True,
    cmap="RdPu",
    linewidths=1,
    linecolor="white",
    square=True,
    annot_kws={
        "fontsize": 11,
        "fontweight": "bold"
    },
    ax=ax
)

style_ax(
    ax,
    "Correlation Heatmap"
)

save_chart(
    fig,
    "05_heatmap.png"
)

# ======================================================
# CHART 6 -- SCATTERPLOT
# ======================================================
fig, ax = plt.subplots(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="Price",
    y="% Change",
    hue="Status",
    palette={"Gainer": "#2DC653", "Loser": COLOR_BRIGHT, "Flat": "#FFC300"},
    s=90,
    edgecolor="white",
    alpha=0.85,
    ax=ax
)

style_ax(
    ax,
    "Price vs Percentage Change"
)

save_chart(
    fig,
    "06_scatter_plot.png"
)

# ======================================================
# CHART 7 -- BOXPLOT
# ======================================================
fig, ax = plt.subplots(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Status",
    y="% Change",
    hue="Status",
    legend=False,
    palette={"Gainer": "#2DC653", "Loser": COLOR_BRIGHT, "Flat": "#FFC300"},
    ax=ax
)

style_ax(
    ax,
    "Percentage Change Spread"
)

save_chart(
    fig,
    "07_boxplot.png"
)

# ======================================================
# OPTIONAL CLEAN DASHBOARD
# ======================================================
fig = plt.figure(
    figsize=(16, 10),
    facecolor="white"
)

gs = fig.add_gridspec(
    2,
    2,
    hspace=0.35,
    wspace=0.25
)

ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])
ax3 = fig.add_subplot(gs[1, 0])
ax4 = fig.add_subplot(gs[1, 1])

# Pie
pie_colors2 = [COLOR_MAP.get(s, COLOR_LIGHT) for s in status_counts.index]
ax1.pie(
    status_counts.values,
    labels=status_counts.index,
    autopct="%1.1f%%",
    colors=pie_colors2,
    startangle=90,
    wedgeprops={
        "edgecolor": "white"
    }
)

ax1.set_title(
    "Market Breadth",
    fontsize=13,
    fontweight="bold"
)

# Histogram
sns.histplot(
    df["Price"],
    bins=20,
    kde=True,
    color=COLOR_BRIGHT,
    edgecolor="white",
    ax=ax2
)

ax2.axvline(
    mean_price,
    color=COLOR_DEEP,
    linestyle="--",
    linewidth=2
)

ax2.set_title(
    "Price Distribution",
    fontsize=13,
    fontweight="bold"
)

# Heatmap
sns.heatmap(
    corr,
    annot=True,
    cmap="RdPu",
    linewidths=1,
    linecolor="white",
    square=True,
    cbar=False,
    ax=ax3
)

ax3.set_title(
    "Correlation Heatmap",
    fontsize=13,
    fontweight="bold"
)

# Scatter
sns.scatterplot(
    data=df,
    x="Price",
    y="% Change",
    hue="Status",
    palette={"Gainer": "#2DC653", "Loser": COLOR_BRIGHT, "Flat": "#FFC300"},
    s=80,
    edgecolor="white",
    ax=ax4
)

ax4.set_title(
    "Price vs Percentage Change",
    fontsize=13,
    fontweight="bold"
)

fig.suptitle(
    "Stock Market Dashboard",
    fontsize=22,
    fontweight="bold",
    color=COLOR_DEEP,
    y=0.97
)

fig.subplots_adjust(
    top=0.88,
    left=0.06,
    right=0.96,
    bottom=0.08
)

save_chart(
    fig,
    "08_dashboard.png"
)


# ======================================================

print(f"\nCharts saved in {PATHS.OUTPUTS_DIR}. Dashboard/report PDF generation removed so daily-changing values stay in the live dashboard.")
